### ISSUE TITLE
RFE: Closing Mate forum

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-desktop.org#61]
Michael our last global forum admin have given up, because no one except me have ever given an answer on his PMs, since 3/4 of a year.
So the forum is unmaintained now.
Users can use distro forums.
@flexiondotorg @monsta @clefebvre 
Let us close the forum in the next week except you guys will jump in and playing a forum Moderator.
I'm really tired about this one year old problem.

**Comment by monsta** [comment]
Well, I'm not even registered there, so I really can't vote... I'm also not ready to be a moderator, that would be an additional work which I don't like (I was a forum moderator several years ago, and eventually I got really tired of that and had to quit).

**Comment by C0bb3r** [comment]
I just typed up, and then deleted, a huge response. I deleted it because I do not believe this should be done in this arena. I deliberately use forum PMs and personal emails for forum discussions so that the MATE project doesn't get dragged into the ever popular Linux ecosystem gossip whirlpool where things get so twisted from the truth it isn't funny.

**Comment by flexiondotorg** [comment]
As discussed the forums are indeed now closed. We do have backups of their last state should we ever decide to reboot them.
