### ISSUE TITLE
Inconsistent licensing

### ISSUE THREAD

**Issue by jorgesumle** [mate-desktop/mate-desktop.org#95]
I was going to contribute to this project, checked the license and everything seemed OK: it was a libre culture license according to <del>`README.md`</del> <ins>`LICENSE.md`</ins>. Then I see the website footer under a completely different license that doesn't allow commercial purposes. It doesn't make sense. Please clarify it.

I need to know the license so that I can know if I should contribute to this project or not. I prefer the Creative Commons license without commercial restriction if I can vote.

**Comment by raveit65** [comment]
Maybe you start with a introduction of yourself :)
And why you need a commercial purpose?

**Comment by jorgesumle** [comment]
> Maybe you start with a introduction of yourself :)

I'm a human, I can code, cook, translate, administer GNU/Linux servers. I don't know if that's what you want to know.

> And why you need a commercial purpose?

I'm against proprietary licenses, I'm a free culture and free software activist, and as such I don't contribute to proprietary projects. I only need to know if this project is free culture or not, just that. I also point out the inconsistency so that you can correct it and avoid misleading people.

**Comment by raveit65** [comment]
We're not a commercial project.

**Comment by jorgesumle** [comment]
> We're not a commercial project.

OK, I guess you mean that you prefer the license with commercial restrictions. Then you need to change the file `LICENSE.md` to use the license you intend.

**Comment by vkareh** [comment]
@raveit65 - I think he means that the website footer shows a [by-nc-sa](https://creativecommons.org/licenses/by-nc-sa/4.0/) license, but the repository shows a [by-sa](https://creativecommons.org/licenses/by-sa/3.0/deed.en_US) license, so that's the discrepancy.

@jorgesumle - we're not a commercial project, but that doesn't mean that we prefer the nc license. I think that fixing the license inconsistency requires voting by the @mate-desktop/core-team. Also, this license is only relevant for this particular repository, the MATE project itself is GPL-2.0, which allows commercial use.

**Comment by monsta** [comment]
@flexiondotorg: I guess it's up to you :slightly_smiling_face:

**Comment by jorgesumle** [comment]
Any news on this issue? I would really like to know if I can contribute to this project.

**Comment by vkareh** [comment]
@jorgesumle - what would prevent you from contributing? Also, what do you want to contribute? This repo is just for the website. Let me know what you have in mind and we can work together. What parts of the license are you concerned about?

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/mate-desktop/mate-desktop.org/pull/131
